from .agent_builder import get_agent
from logs import logger

def run_support_agent(user_query:str):
    """
    Process a support query using the AI agent.
    Args:
        query (Query): User input wrapped in a Pydantic model.
    Returns:
        dict: Result generated by the support agent.
    """
    try:
        logger.info(f"Invoking agent for query: {user_query}")
        agent = get_agent()
        response = agent.invoke(user_query)
        return {"response": response}
    except (ValueError,AttributeError) as e:
        logger.info("getting agent error")
        return {"message":f"unable to call the agent{e}"}
    except Exception:
        logger.exception("Unexpected error during agent execution.")
        return {"error": "An unexpected error occurred while processing your query."}